apiVersion: apps/v1
kind: Deployment
metadata:
  name: vrf
  labels:
    app: vrf
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vrf
  template:
    metadata:
      labels:
        app: vrf
    spec:
      containers:
        - name: vrf-container
          image: ghcr.io/p7-vcra/vessel-route-forecasting/vrf:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          command: ['python', 'src/app.py', '--port', '8080']
          volumeMounts:
            - name: vrf-volume
              mountPath: /app/data
          env:
            - name: MODEL_PATH
              value: /app/data/model/model.keras
      volumes:
        - name: vrf-volume
          hostPath:
            path: /home/ubuntu/vcra/vrf/data
      imagePullSecrets:
        - name: ghcr-secret

---
apiVersion: v1
kind: Service
metadata:
  name: vrf-service
spec:
  selector:
    app: vrf
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
