apiVersion: apps/v1
kind: Deployment
metadata:
  name: tensorflow-app
  labels:
    app: tensorflow-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tensorflow-app
  template:
    metadata:
      labels:
        app: tensorflow-app
    spec:
      containers:
        - name: tensorflow-app-container
          image: tensorflow/tensorflow:latest-gpu
          ports:
            - containerPort: 8888
          resources:
            limits:
              nvidia.com/gpu: 1 # Specify GPU resources for this container
          volumeMounts:
            - name: app-volume
              mountPath: /app
          command: ['python', 'src/app.py', '--port', '8888']
      volumes:
        - name: app-volume
          hostPath:
            path: /path/on/host # Adjust this path to where your app is stored
            type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: tensorflow-app-service
spec:
  selector:
    app: tensorflow-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
  type: LoadBalancer # This exposes your app externally
