apiVersion: apps/v1
kind: Deployment
metadata:
  name: vrf
  labels:
    app: vrf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vrf
  template:
    metadata:
      labels:
        app: vrf
    spec:
      containers:
        - name: vrf-container
          image: ghcr.io/p7-vcra/vessel-route-forecasting/vrf:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          command: ['python', 'src/app.py', '--port', '8080']
          volumeMounts:
            - name: vrf-volume
              mountPath: /app/data
          env:
            - name: MODEL_PATH
              value: /app/data/model/model.keras
            - name: NORM_PARAMS_PATH
              value: /app/data/model/norm_params.json
          resources:
            requests:
              cpu: '100m'
              memory: 1Gi
            limits:
              cpu: '500m'
              memory: 2Gi
      volumes:
        - name: vrf-volume
          hostPath:
            path: /home/ubuntu/vcra/vrf/data
      imagePullSecrets:
        - name: ghcr-secret

---
apiVersion: v1
kind: Service
metadata:
  name: vrf-service
spec:
  selector:
    app: vrf
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vrf-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vrf
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
