name: Deploy to K3s

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clean up Docker space
        run: |
          docker system prune -af
          docker volume prune -f

      - name: Build Docker image
        run: |
          docker build -t vrf:latest .

      - name: Load image into K3s cluster
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          mkdir -p ~/.kube
          echo "$KUBECONFIG" > ~/.kube/config
          ctr -n k8s.io images import $(docker save vrf:latest | docker load)

      - name: Deploy application to K3s
        run: |
          kubectl apply -f deploy.yaml
