name: Deploy to K3s

on:
  push:
    branches:
      - main

permissions:
  packages: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with GitHub Container Registry
        env:
          CR_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin || exit 1

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/vrf:${{ github.sha }}
            ghcr.io/${{ github.repository }}/vrf:latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/vrf:cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}/vrf:cache,mode=max

      - name: Update image tag in deploy.yaml
        run: |
          sed -i "s|ghcr.io/${{ github.repository }}/vrf:latest|ghcr.io/${{ github.repository }}/vrf:${{ github.sha }}|g" deploy.yaml

      - name: Set up Kubeconfig
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          mkdir -p ~/.kube
          echo "$KUBECONFIG" > ~/.kube/config

      - name: Verify kubectl version
        run: |
          kubectl version --client

      - name: Deploy application to K3s
        run: |
          kubectl apply -f deploy.yaml
