name: Deploy to K3s

on:
  push:
    branches:
      - main

permissions:
  packages: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up cache for Docker layers
        uses: actions/cache@v4
        with:
          path: /home/runner/.cache/docker
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Set up GHCR Authentication
        env:
          CR_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/vrf:${{ github.sha }}
            ghcr.io/${{ github.repository }}/vrf:latest
          cache-from: type=local,src=/home/runner/.cache/docker
          cache-to: type=local,dest=/home/runner/.cache/docker

      - name: Update image tag in deploy.yaml
        run: |
          sed -i "s|ghcr.io/${{ github.repository }}/vrf:latest|ghcr.io/${{ github.repository }}/vrf:${{ github.sha }}|g" deploy.yaml

      - name: Set up Kubeconfig
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          mkdir -p ~/.kube
          echo "$KUBECONFIG" > ~/.kube/config

      - name: Deploy application to K3s
        run: |
          kubectl apply -f deploy.yaml
