name: Test and Lint

on:
  push:
  pull_request:
    branches:
      - main

permissions:
  packages: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Fetch model
        env:
          MODEL_DIR: data/model
          MODEL_NAME: model.keras
        run: |
          mkdir -p ${{ env.MODEL_DIR }}
          scp -i ~/.ssh/id_rsa ubuntu@${{ secrets.HOST }}:/home/ubuntu/vcra/vrf/${{ env.MODEL_DIR }}/${{ env.MODEL_NAME }} ${{ env.MODEL_DIR }}

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with Ruff
        run: |
          ruff check src
          ruff format src

      - name: Test with pytest
        run: |
          pytest
