name: Build and Deploy to K3s

on:
  push:
  pull_request:
    branches:
      - main

permissions:
  packages: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with Ruff
        run: |
          ruff check src
          ruff format src

      - name: Test with pytest
        run: |
          pytest
